# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-06-18 12:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_auto_20190612_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Language', verbose_name='Language'),
        ),
    ]
