# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-06-20 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_auto_20190613_1013'),
        ('manager', '0008_auto_20190612_1819'),
    ]

    operations = [
    ]
